version: '3.8'

services:
  migrator:
    build:
      context: .
      dockerfile: Dockerfile
    image: migrator_img
    command: truffle migrate --network env
    volumes:
      - ./ethereum:/app/
      - ./env:/env

  ton_migrator:
    image: migrator_img
    command: /node_modules/.bin/mocha /app/test/1-setup-event-configurations.js
    volumes:
      - ./env:/app/env
      - ./free-ton:/app/
      - ./free-ton/build:/app/free-ton/build
