version: '3.8'

services:
  ganache:
    image: trufflesuite/ganache-cli
    command: --mnemonic "${ETH_SEED}" --accounts ${RELAYS_AMOUNT} --blockTime 5
    env_file:
      - settings.env
    ports:
      - 8545:8545

  eth_migrator:
    build:
      context: .
      dockerfile: Dockerfile
    image: migrator_img
    command: wait-for-it.sh -s -t 0 ganache:8545 -- /node_modules/.bin/truffle migrate --network development
    env_file:
      - settings.env
    volumes:
    - ./ethereum:/app/
    depends_on:
      - ganache

  ton_node:
    image: tonlabs/local-node
    environment:
      - USER_AGREEMENT=yes
    ports:
      - 80:80

  ton_migrator:
    image: migrator_img
    command: bash -c "sleep 10 && DETERMINE_DEPLOY=1 npm run migrate-ton && /node_modules/.bin/mocha test/ --exit"
    env_file:
      - settings.env
    volumes:
      - ./free-ton:/app/
      - ./free-ton:/app/free-ton
      - ./free-ton/build:/app/free-ton/build
      - ./package.json:/app/package.json
      - ./env:/app/env
    depends_on:
      - ton_node
